name: Deploy net8.0 Files to Server

# 触发条件：在 push 事件时触发
on: 
  push:
    branches:
      - PaoPaoTang # 可以根据你的分支调整

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 检查 Bin/Release/net8.0 是否有更改
    - name: Check for changes in Bin/Release/net8.0
      id: check_bin_changes
      run: |
        if git diff --exit-code --quiet HEAD^ HEAD -- Bin/Release/net8.0; then
          echo "no changes" 
          echo "::set-output name=bin_files_changed::false"
        else
          echo "files changed" 
          echo "::set-output name=bin_files_changed::true"
        fi

    # 检查 Config/Binary 是否有更改
    - name: Check for changes in Config/Binary
      id: check_config_changes
      run: |
        if git diff --exit-code --quiet HEAD^ HEAD -- Config/Binary; then
          echo "no changes"
          echo "::set-output name=config_files_changed::false"
        else
          echo "files changed"
          echo "::set-output name=config_files_changed::true"
        fi

    # 部署 Bin/Release/net8.0 文件夹，如果有更改
    - name: Deploy Bin/Release/net8.0 files to server
      if: steps.check_bin_changes.outputs.bin_files_changed == 'true'
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}  # 使用密码登录
        source: "Bin/Release/net8.0/*"  # 要上传的文件
        target: "/www/wwwroot/Saber/Server"  # 目标路径

    # 部署 Config/Binary 文件夹，如果有更改
    - name: Deploy Config/Binary files to server
      if: steps.check_config_changes.outputs.config_files_changed == 'true'
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}  # 使用密码登录
        source: "Config/Binary/*"  # 要上传的文件
        target: "/www/wwwroot/Saber/Server/Bin/Release/net8.0"  # 目标路径
