name: Deploy net8.0 Files to Server

# 触发条件：在 push 事件时触发
on: 
  push:
    branches:
      - main # 可以根据你的分支调整

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for changes in Bin\Debug\net8.0
      id: check_changes
      run: |
        if git diff --exit-code --quiet HEAD^ HEAD -- Bin/Debug/net8.0; then
          echo "no changes" 
          echo "::set-output name=files_changed::false"
        else
          echo "files changed" 
          echo "::set-output name=files_changed::true"
        fi

    # 使用条件步骤：如果有文件变化则继续执行部署
    - name: Deploy files to server
      if: steps.check_changes.outputs.files_changed == 'true'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}   # 在 GitHub Secrets 中配置服务器信息
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "Bin/Debug/net8.0/*"        # 上传 net8.0 文件夹的内容
        target: "/www/wwwroot/Saber/Server"  # 服务器上的目标路径
